

name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  build:
   
    runs-on: ubuntu-latest

    
    steps:
     
      - uses: actions/checkout@v4
      - name: build image
        run: |
             docker build -t ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}} .
             docker build -t ${{secrets.REGISTRY_USER}}/portfolio .

      
      - name: push image
        run: |
            docker login -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
            docker push ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}}
            docker push ${{secrets.REGISTRY_USER}}/portfolio

  deploy:
    needs: build
    run-on: ubuntu-latest
    steps:
     - name: SSH to server
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
        # port: ${{ secrets.PORT }}
         script: |
                  docker rm -f resume
                  docker run -d --nameresume -p 8080:5001 ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}}
          
        